import React,{useMemo,useState} from "react";
import {createRoot} from "react-dom/client";
import {LayoutDashboard,WalletCards,ArrowLeftRight,BarChart3,Users,GitBranch,CircleDollarSign,Plus,CheckCircle2,History,Scale,FileDown,Calculator,CalendarDays} from "lucide-react";
import {LineChart,Line,XAxis,YAxis,Tooltip,ResponsiveContainer,CartesianGrid,PieChart,Pie,Cell,BarChart,Bar,Legend} from "recharts";
import "./styles.css";

const marketData=[
 {date:"2026-08-01",TCS:3900,HDFC:1650,Reliance:1390,Apple:220,Microsoft:500,NIFTY:24500,SENSEX:80200,SP500:6300,NASDAQ:20900,FTSE:9100},
 {date:"2026-08-08",TCS:3950,HDFC:1685,Reliance:1420,Apple:223,Microsoft:505,NIFTY:24750,SENSEX:80900,SP500:6340,NASDAQ:21100,FTSE:9180},
 {date:"2026-08-15",TCS:4020,HDFC:1700,Reliance:1445,Apple:226,Microsoft:512,NIFTY:24900,SENSEX:81500,SP500:6380,NASDAQ:21300,FTSE:9220},
 {date:"2026-08-22",TCS:4080,HDFC:1720,Reliance:1460,Apple:230,Microsoft:518,NIFTY:25100,SENSEX:82200,SP500:6420,NASDAQ:21550,FTSE:9300}
];
const seed={
 CL001:{id:"CL001",name:"Aarav Mehta",type:"Mid-Tier Client",base:"INR",risk:"Moderate",benchmark:"NIFTY 50",benchmarkReturn:3.6,cash:{INR:2150000,USD:25000,EUR:10000,GBP:5000},fx:{INR:1,USD:88.10,EUR:103.20,GBP:118.50},
 holdings:[
  {id:1,name:"HDFC Bank",asset:"Equity",ccy:"INR",qty:1200,buyPrice:1650,buyDate:"2026-08-08"},
  {id:2,name:"Reliance Industries",asset:"Equity",ccy:"INR",qty:900,buyPrice:1390,buyDate:"2026-08-01"},
  {id:3,name:"TCS",asset:"Equity",ccy:"INR",qty:420,buyPrice:3950,buyDate:"2026-08-08"},
  {id:4,name:"ICICI Prudential MF",asset:"Mutual Fund",ccy:"INR",qty:8500,buyPrice:160,buyDate:"2026-08-01",marketPrice:168},
  {id:5,name:"7.20% Govt Bond",asset:"Bond",ccy:"INR",qty:120000,buyPrice:97,buyDate:"2026-07-15",marketPrice:100}],
 trades:[
  {date:"12 Aug 2026",type:"BUY",security:"TCS",asset:"Equity",qty:420,price:3950,ccy:"INR",status:"Posted"},
  {date:"08 Aug 2026",type:"BUY",security:"HDFC Bank",asset:"Equity",qty:1200,price:1650,ccy:"INR",status:"Posted"},
  {date:"29 Jul 2026",type:"SELL",security:"ITC",asset:"Equity",qty:500,price:465,ccy:"INR",status:"Backdated"},
  {date:"15 Jul 2026",type:"BUY",security:"Govt Bond",asset:"Bond",qty:120000,price:97,ccy:"INR",status:"Posted"}]},
 CL002:{id:"CL002",name:"Vikram Sharma",type:"High-Net-Worth Client",base:"INR",risk:"Moderate-Conservative",benchmark:"S&P 500",benchmarkReturn:5.9,cash:{INR:14600000,USD:180000,EUR:40000,GBP:25000},fx:{INR:1,USD:88.10,EUR:103.20,GBP:118.50},
 holdings:[
  {id:1,name:"Apple Inc.",asset:"Equity",ccy:"USD",qty:2200,buyPrice:220,buyDate:"2026-08-01"},
  {id:2,name:"Microsoft",asset:"Equity",ccy:"USD",qty:1400,buyPrice:500,buyDate:"2026-08-08"},
  {id:3,name:"Gold ETF",asset:"ETF",ccy:"INR",qty:8500,buyPrice:65,buyDate:"2026-08-01",marketPrice:72},
  {id:4,name:"US Treasury 10Y",asset:"Bond",ccy:"USD",qty:180000,buyPrice:96,buyDate:"2026-08-01",marketPrice:98},
  {id:5,name:"Money Market Fund",asset:"Mutual Fund",ccy:"USD",qty:9000000,buyPrice:1,buyDate:"2026-07-15",marketPrice:1}],
 trades:[
  {date:"20 Aug 2026",type:"BUY",security:"Microsoft",asset:"Equity",qty:1400,price:500,ccy:"USD",status:"Posted"},
  {date:"14 Aug 2026",type:"BUY",security:"Apple Inc.",asset:"Equity",qty:2200,price:220,ccy:"USD",status:"Posted"},
  {date:"02 Aug 2026",type:"BUY",security:"US Treasury 10Y",asset:"Bond",qty:180000,price:96,ccy:"USD",status:"Posted"},
  {date:"18 Jul 2026",type:"SELL",security:"Alphabet",asset:"Equity",qty:700,price:182,ccy:"USD",status:"Backdated"}]}
};
const colors=["#2f75b5","#00a3a3","#7a68a8","#f4b400","#7d8a99"];
const periods={ "1 Month":1,"3 Months":3,"6 Months":6,"YTD":8,"1 Year":12 };
const money=(n,ccy="INR")=>new Intl.NumberFormat("en-IN",{style:"currency",currency:ccy,maximumFractionDigits:0}).format(n);
const daysBetween=(a,b)=>Math.max(0,Math.round((new Date(b)-new Date(a))/86400000));
const priceFor=(h)=>{if(h.marketPrice!=null)return h.marketPrice; const latest=marketData[marketData.length-1]; if(h.name==="TCS")return latest.TCS;if(h.name==="HDFC Bank")return latest.HDFC;if(h.name==="Reliance Industries")return latest.Reliance;if(h.name==="Apple Inc.")return latest.Apple;if(h.name==="Microsoft")return latest.Microsoft;return h.buyPrice};
const calcHolding=(h,c)=>{const mp=priceFor(h),buy=h.qty*h.buyPrice*c.fx[h.ccy],mv=h.qty*mp*c.fx[h.ccy],mtm=mv-buy;return {...h,marketPrice:mp,buyValue:buy,marketValue:mv,mtm,mtmPct:buy?mtm/buy*100:0,holdingPeriod:daysBetween(h.buyDate,"2026-08-22")}};
const cashValue=c=>Object.entries(c.cash).reduce((s,[k,v])=>s+v*c.fx[k],0);
const baseValue=c=>cashValue(c)+c.holdings.reduce((s,h)=>s+calcHolding(h,c).marketValue,0);

function App(){
 const [clients,setClients]=useState(seed),[client,setClient]=useState("CL001"),[page,setPage]=useState("Dashboard"),[toast,setToast]=useState("");
 const [statement,setStatement]=useState({from:"2026-08-01",to:"2026-08-22"});
 const c=clients[client];
 const notify=x=>{setToast(x);setTimeout(()=>setToast(""),2500)};
 const recordTrade=t=>{
  setClients(prev=>{const old=prev[client],cash={...old.cash},hold=old.holdings.map(x=>({...x})),amt=t.qty*t.price;cash[t.ccy]=(cash[t.ccy]||0)+(t.type==="BUY"?-amt:amt);const idx=hold.findIndex(h=>h.name.toLowerCase()===t.security.toLowerCase()&&h.ccy===t.ccy);
   if(t.type==="BUY"){if(idx>=0){const h=hold[idx],q=h.qty+t.qty;h.buyPrice=(h.qty*h.buyPrice+t.qty*t.price)/q;h.qty=q}else hold.push({id:Date.now(),name:t.security,asset:t.asset,ccy:t.ccy,qty:t.qty,buyPrice:t.price,buyDate:t.date})}
   else if(idx>=0){hold[idx].qty=Math.max(0,hold[idx].qty-t.qty);if(!hold[idx].qty)hold.splice(idx,1)}
   return {...prev,[client]:{...old,cash,holdings:hold,trades:[t,...old.trades]}}});
  notify("Trade recorded — cash and holdings updated");
 };
 const nav=[["Dashboard",LayoutDashboard],["Trade Management",ArrowLeftRight],["Portfolio",WalletCards],["Cash & FX",CircleDollarSign],["Performance & Risk",BarChart3],["Client Comparison",Scale],["Statement",FileDown],["Clients",Users],["System Architecture",GitBranch]];
 return <div className="app"><aside className="side"><div className="brand"><div className="logo">P</div><div><b>Portfolio Reporting</b><small>Wealth Management</small></div></div><div className="nav">{nav.map(([n,I])=><button className={page===n?"active":""} onClick={()=>setPage(n)} key={n}><I size={17}/>{n}</button>)}</div><div className="sidefoot">Prototype · Fixed market dataset<br/>Vercel ready · 2026</div></aside>
 <main className="main"><header className="top"><div><div className="eyebrow">Client Reporting System</div><h1>{page}</h1><p>Transactions → valuation → MTM → FX → benchmark → statement</p></div><div className="controls"><select value={client} onChange={e=>setClient(e.target.value)}><option value="CL001">CL001 · Aarav Mehta</option><option value="CL002">CL002 · Vikram Sharma</option></select><span className="date">22 Aug 2026</span></div></header>{toast&&<div className="toast"><CheckCircle2 size={16}/>{toast}</div>}
 {page==="Dashboard"&&<Dashboard c={c}/>} {page==="Trade Management"&&<TradeManagement c={c} onAdd={recordTrade}/>} {page==="Portfolio"&&<Portfolio c={c}/>} {page==="Cash & FX"&&<CashFX c={c}/>} {page==="Performance & Risk"&&<Performance c={c}/>} {page==="Client Comparison"&&<Comparison clients={clients}/>} {page==="Statement"&&<Statement c={c} range={statement} setRange={setStatement}/>} {page==="Clients"&&<Clients clients={clients} selected={client} setClient={setClient}/>} {page==="System Architecture"&&<Architecture/>} 
 </main></div>
}
function Metric({l,v,f,cls=""}){return <div className="card"><small className="label">{l}</small><strong className={cls}>{v}</strong><span>{f}</span></div>}
function Metrics({c}){let hs=c.holdings.map(h=>calcHolding(h,c)),pnl=hs.reduce((s,h)=>s+h.mtm,0);return <div className="grid4"><Metric l="Portfolio Value" v={money(baseValue(c))} f="Consolidated INR"/><Metric l="Cash & Liquidity" v={money(cashValue(c))} f="INR / USD / EUR / GBP"/><Metric l="MTM P&L" v={(pnl>=0?"+":"")+money(pnl)} cls={pnl>=0?"green":"red"} f="Current market value vs buy value"/><Metric l="Portfolio Beta" v={c.id==="CL001"?"0.91":"0.72"} f={`vs ${c.benchmark}`}/></div>}
function Section({title,sub}){return <div className="sectionhead"><div><h3>{title}</h3>{sub&&<span>{sub}</span>}</div></div>}
function Dashboard({c}){return <><Metrics c={c}/><div className="two"><div className="card"><Section title="Portfolio vs Benchmark" sub={`${c.benchmark} · illustrative historical dataset`}/><Chart benchmark={c.benchmark}/></div><Allocation c={c}/></div><div className="card section"><Section title="Top Holdings" sub="Buy value, market value and MTM"/><Holdings c={c}/></div><div className="two"><div className="card"><Section title="Risk Snapshot"/><div className="riskgrid"><R label="Beta" v={c.id==="CL001"?"0.91":"0.72"}/><R label="Sharpe" v={c.id==="CL001"?"1.18":"1.46"}/><R label="Delta" v={c.id==="CL001"?"0.84":"0.67"}/><R label="Return" v={c.id==="CL001"?"+4.2%":"+6.8%"}/></div></div><div className="card"><Section title="Client Profile"/><div className="profile"><b>{c.name}</b><span>{c.type}</span><span>Risk: {c.risk}</span><span>Base: {c.base}</span><span>Benchmark: {c.benchmark}</span></div></div></div></>}
function Chart({benchmark="NIFTY 50"}){const keys={ "NIFTY 50":"NIFTY","SENSEX":"SENSEX","S&P 500":"SP500","NASDAQ Composite":"NASDAQ","FTSE 100":"FTSE"};const key=keys[benchmark]||"NIFTY";const data=marketData.map((x,i)=>({m:x.date.slice(5),p:100+i*2.2,b:100+(x[key]/marketData[0][key]-1)*100}));return <div className="chart"><ResponsiveContainer><LineChart data={data}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="m"/><YAxis/><Tooltip/><Legend/><Line dataKey="p" name="Portfolio" stroke="#2f75b5" strokeWidth={3} dot={false}/><Line dataKey="b" name={benchmark} stroke="#8996a5" strokeWidth={2} strokeDasharray="5 5" dot={false}/></LineChart></ResponsiveContainer></div>}
function R({label,v}){return <div className="risk"><span>{label}</span><b>{v}</b></div>}
function Allocation({c}){let m={};c.holdings.forEach(h=>m[h.asset]=(m[h.asset]||0)+calcHolding(h,c).marketValue);let data=Object.entries(m).map(([name,value])=>({name,value}));return <div className="card"><Section title="Asset Allocation"/><div className="alloc"><PieChart width={190} height={190}><Pie data={data} dataKey="value" innerRadius={56} outerRadius={82} paddingAngle={3}>{data.map((_,i)=><Cell key={i} fill={colors[i%colors.length]}/>)}</Pie></PieChart><div>{data.map((x,i)=><div className="legendrow" key={x.name}><span><i style={{background:colors[i%colors.length]}}/>{x.name}</span><b>{(x.value/baseValue(c)*100).toFixed(1)}%</b></div>)}</div></div></div>}
function Holdings({c}){return <><table><thead><tr><th>Security</th><th>Asset</th><th>CCY</th><th>Qty</th><th>Buy Value</th><th>Current Value</th><th>Gain/Loss</th><th>Holding Period</th></tr></thead><tbody>{c.holdings.map(h=>{let x=calcHolding(h,c);return <tr key={h.id}><td><b>{h.name}</b></td><td>{h.asset}</td><td>{h.ccy}</td><td>{h.qty.toLocaleString()}</td><td>{money(x.buyValue)}</td><td>{money(x.marketValue)}</td><td className={x.mtm>=0?"green":"red"}>{x.mtm>=0?"+":""}{money(x.mtm)}<small className="pct"> ({x.mtmPct.toFixed(2)}%)</small></td><td>{x.holdingPeriod} days</td></tr>})}</tbody></table><CalculationBox c={c} h={c.holdings[0]}/><MarketFeed c={c}/></>}
function CalculationBox({c,h}){if(!h)return null;let x=calcHolding(h,c);return <div className="calcbox"><div className="calc-title"><Calculator size={17}/> How MTM is calculated — {h.name}</div><div className="calc-grid"><div><span>Quantity</span><b>{h.qty.toLocaleString()}</b></div><div><span>Buy Price</span><b>{money(h.buyPrice,h.ccy)}</b></div><div><span>Market Price</span><b>{money(x.marketPrice,h.ccy)}</b></div><div><span>Buy Value</span><b>{h.qty} × {h.buyPrice.toLocaleString()} = {money(h.qty*h.buyPrice*c.fx[h.ccy])}</b></div><div><span>Market Value</span><b>{h.qty} × {x.marketPrice.toLocaleString()} = {money(x.marketValue)}</b></div><div><span>MTM P&L</span><b>{money(x.marketValue-(h.qty*h.buyPrice*c.fx[h.ccy]))}</b></div><div><span>MTM Return</span><b>{x.mtmPct.toFixed(2)}%</b></div><div><span>Holding Period</span><b>{x.holdingPeriod} days</b></div></div><p>Formula: <b>MTM = Market Value − Buy Value</b> · MTM % = MTM ÷ Buy Value × 100</p></div>}
function MarketFeed({c}){let latest=marketData[marketData.length-1],prev=marketData[marketData.length-2];const rows=c.holdings.filter(h=>["TCS","HDFC Bank","Reliance Industries","Apple Inc.","Microsoft"].includes(h.name)).map(h=>{let key=h.name==="TCS"?"TCS":h.name==="HDFC Bank"?"HDFC":h.name==="Reliance Industries"?"Reliance":h.name==="Apple Inc."?"Apple":"Microsoft";return {name:h.name,prev:prev[key],current:latest[key],value:calcHolding(h,c).marketValue}});return <div className="feed card"><Section title="Market Price Feed" sub="External market-data layer represented by a fixed historical dataset"/><div className="feedmeta"><span><b>Source:</b> External Market Data Feed</span><span><b>Status:</b> 🟢 Dataset Available</span><span><b>Last Updated:</b> 22 Aug 2026, 16:00 IST</span><span><b>Mode:</b> Historical / Illustrative</span></div><table><thead><tr><th>Security</th><th>Previous Price</th><th>Market Price</th><th>Current Market Value</th></tr></thead><tbody>{rows.map(r=><tr key={r.name}><td><b>{r.name}</b></td><td>{r.prev.toLocaleString()}</td><td><b>{r.current.toLocaleString()}</b></td><td>{money(r.value)}</td></tr>)}</tbody></table><div className="feedformula"><b>MTM / Market Value uses the current market price from this feed.</b> &nbsp; Market Value = Quantity × Current Market Price</div></div>}
function Portfolio({c}){return <><div className="card"><Section title="Portfolio Holdings" sub="Buy value, current value, gain/loss and holding period"/><Holdings c={c}/></div></>}
function TradeManagement({c,onAdd}){const [form,setForm]=useState({type:"BUY",security:"",asset:"Equity",qty:"",price:"",ccy:"INR",date:"2026-08-22",backdated:false});const submit=e=>{e.preventDefault();if(!form.security||!form.qty||!form.price)return;onAdd({...form,qty:Number(form.qty),price:Number(form.price),status:form.backdated?"Backdated":"Posted",date:new Date(form.date+"T12:00:00").toLocaleDateString("en-GB",{day:"2-digit",month:"short",year:"numeric"})});setForm({...form,security:"",qty:"",price:"",backdated:false})};return <><div className="two"><div className="card"><Section title="Manual Trade Entry" sub="Current or historical BUY / SELL transaction"/><form onSubmit={submit} className="form"><label>Trade Type<select value={form.type} onChange={e=>setForm({...form,type:e.target.value})}><option>BUY</option><option>SELL</option></select></label><label>Security<input value={form.security} onChange={e=>setForm({...form,security:e.target.value})} placeholder="e.g. TCS"/></label><label>Asset Class<select value={form.asset} onChange={e=>setForm({...form,asset:e.target.value})}><option>Equity</option><option>Bond</option><option>ETF</option><option>Mutual Fund</option></select></label><label>Quantity<input type="number" min="1" value={form.qty} onChange={e=>setForm({...form,qty:e.target.value})}/></label><label>Price<input type="number" min="0" step="0.01" value={form.price} onChange={e=>setForm({...form,price:e.target.value})}/></label><label>Currency<select value={form.ccy} onChange={e=>setForm({...form,ccy:e.target.value})}><option>INR</option><option>USD</option><option>EUR</option><option>GBP</option></select></label><label>Trade Date<input type="date" value={form.date} onChange={e=>setForm({...form,date:e.target.value})}/></label><label className="check"><input type="checkbox" checked={form.backdated} onChange={e=>setForm({...form,backdated:e.target.checked})}/> Mark as backdated</label><button className="primary"><Plus size={16}/> Record Trade & Update Portfolio</button></form></div><div className="card"><Section title="Processing Flow"/><div className="flowmini">{["Trade recorded","Cash ledger updated","Holdings updated","Market price applied","MTM recalculated","Reporting refreshed"].map((x,i)=><React.Fragment key={x}><div>{i+1}. {x}</div>{i<5&&<span>↓</span>}</React.Fragment>)}</div></div></div><div className="card section"><Section title="Transaction History"/><Trades c={c}/></div></>}
function Trades({c}){return <table><thead><tr><th>Date</th><th>Type</th><th>Security</th><th>Asset</th><th>Qty</th><th>Price</th><th>CCY</th><th>Status</th></tr></thead><tbody>{c.trades.map((t,i)=><tr key={i}><td>{t.date}</td><td>{t.type}</td><td><b>{t.security}</b></td><td>{t.asset}</td><td>{t.qty.toLocaleString()}</td><td>{t.price.toLocaleString()}</td><td>{t.ccy}</td><td><em className={t.status==="Backdated"?"back":""}>{t.status}</em></td></tr>)}</tbody></table>}
function CashFX({c}){let rows=Object.entries(c.cash).map(([ccy,bal])=>({ccy,bal,rate:c.fx[ccy],base:bal*c.fx[ccy]}));return <><div className="card"><Section title="Multi-Currency Cash Balances" sub="Consolidated to client base currency INR"/><table><thead><tr><th>Currency</th><th>Cash Balance</th><th>FX Rate → INR</th><th>INR Equivalent</th></tr></thead><tbody>{rows.map(r=><tr key={r.ccy}><td><b>{r.ccy}</b></td><td>{r.bal.toLocaleString()} {r.ccy}</td><td>{r.rate.toFixed(2)}</td><td><b>{money(r.base)}</b></td></tr>)}</tbody></table></div><div className="two"><div className="card"><Section title="FX Calculation"/><div className="calcbox small"><p>Example: USD Cash = <b>$25,000</b></p><p>USD/INR = <b>₹88.10</b></p><p>INR Value = $25,000 × ₹88.10 = <b>₹22,02,500</b></p></div></div><div className="card"><Section title="Total Cash in INR"/><div className="big">{money(rows.reduce((s,r)=>s+r.base,0))}</div><span className="muted">INR + USD + EUR + GBP</span></div></div></>}
function Performance({c}){const [bm,setBm]=useState(c.benchmark),[period,setPeriod]=useState("1 Month");let ret=c.id==="CL001"?4.2:6.8;let bret={ "NIFTY 50":3.6,"SENSEX":2.9,"S&P 500":5.9,"NASDAQ Composite":6.5,"FTSE 100":2.7}[bm];let factor=period==="1 Year"?3:period==="6 Months"?2:period==="YTD"?2.35:period==="3 Months"?1.5:1;let pr=ret*factor,br=bret*factor;return <><div className="toolbar card"><label>Benchmark<select value={bm} onChange={e=>setBm(e.target.value)}><option>NIFTY 50</option><option>SENSEX</option><option>S&P 500</option><option>NASDAQ Composite</option><option>FTSE 100</option></select></label><label>Period<select value={period} onChange={e=>setPeriod(e.target.value)}>{Object.keys(periods).map(x=><option key={x}>{x}</option>)}</select></label><span className="dataset">Illustrative historical market dataset</span></div><div className="grid4"><Metric l="Portfolio Return" v={`+${pr.toFixed(1)}%`} f={period}/><Metric l="Benchmark Return" v={`+${br.toFixed(1)}%`} f={bm}/><Metric l="Outperformance" v={`${(pr-br)>=0?"+":""}${(pr-br).toFixed(1)}%`} cls="green" f="vs benchmark"/><Metric l="Sharpe Ratio" v={c.id==="CL001"?"1.18":"1.46"} f="Risk-adjusted return"/></div><div className="card section"><Section title={`${bm} Comparison`} sub={`${period} · portfolio vs selected market index`}/><Chart benchmark={bm}/><div className="calcbox small"><p><b>Outperformance = Portfolio Return − Benchmark Return</b></p><p>{pr.toFixed(1)}% − {br.toFixed(1)}% = <b>{(pr-br).toFixed(1)}%</b></p></div></div></>}
function Comparison({clients}){let a=clients.CL001,b=clients.CL002;let rows=[["Client type",a.type,b.type],["Portfolio value",money(baseValue(a)),money(baseValue(b))],["Risk profile",a.risk,b.risk],["Benchmark",a.benchmark,b.benchmark],["Return","+4.2%","+6.8%"],["Portfolio Beta","0.91","0.72"],["Sharpe Ratio","1.18","1.46"]];return <div className="card"><Section title="Client Comparison" sub="Same reporting engine applied to two materially different portfolios"/><table><thead><tr><th>Metric</th><th>CL001 · Mid-Tier</th><th>CL002 · High-Net-Worth</th></tr></thead><tbody>{rows.map(r=><tr key={r[0]}><td><b>{r[0]}</b></td><td>{r[1]}</td><td>{r[2]}</td></tr>)}</tbody></table></div>}
function Statement({c,range,setRange}){const download=()=>window.print();return <div className="statement"><div className="card no-print"><Section title="Client Statement" sub="Generate a presentation-ready statement from the fixed historical dataset"/><div className="statement-controls"><label>From <input type="date" value={range.from} onChange={e=>setRange({...range,from:e.target.value})}/></label><label>To <input type="date" value={range.to} onChange={e=>setRange({...range,to:e.target.value})}/></label><button className="primary" onClick={download}><FileDown size={16}/> Download / Save as PDF</button></div><p className="hint">Tip: the browser print dialog lets you choose “Save as PDF”.</p></div><div className="card printable"><div className="statementhead"><div><div className="eyebrow">PORTFOLIO STATEMENT</div><h2>{c.name}</h2><span>{c.id} · {c.type} · Base Currency {c.base}</span></div><div><b>Statement Period</b><br/>{range.from} → {range.to}</div></div><div className="grid4"><Metric l="Portfolio Value" v={money(baseValue(c))} f="As of 22 Aug 2026"/><Metric l="Cash" v={money(cashValue(c))} f="All currencies in INR"/><Metric l="MTM P&L" v={money(c.holdings.map(h=>calcHolding(h,c).mtm).reduce((a,b)=>a+b,0))} f="Unrealized"/><Metric l="Benchmark" v={c.benchmark} f="Selected market index"/></div><Section title="Holdings & MTM"/><Holdings c={c}/><Section title="Cash Balances"/><CashMini c={c}/><Section title="Transactions"/><Trades c={c}/><div className="statementnote">Market prices used for MTM are from the built-in <b>Illustrative Historical Market Dataset</b>. This prototype does not claim live exchange connectivity.</div></div></div>}
function CashMini({c}){return <table><thead><tr><th>Currency</th><th>Balance</th><th>FX to INR</th><th>INR Equivalent</th></tr></thead><tbody>{Object.entries(c.cash).map(([k,v])=><tr key={k}><td>{k}</td><td>{v.toLocaleString()}</td><td>{c.fx[k].toFixed(2)}</td><td>{money(v*c.fx[k])}</td></tr>)}</tbody></table>}
function Clients({clients,selected,setClient}){return <div className="clientgrid">{Object.values(clients).map(c=><div className={"card client "+(selected===c.id?"selected":"")} onClick={()=>setClient(c.id)} key={c.id}><span className="eyebrow">{c.id}</span><h2>{c.name}</h2><p>{c.type}</p><div className="big">{money(baseValue(c))}</div><span>Portfolio value · Base INR</span><div className="tags"><em>{c.risk}</em><em>{c.benchmark}</em></div></div>)}</div>}
function Architecture(){return <div className="card arch"><Section title="System Architecture & Reporting Flow" sub="Two data sources feed valuation, risk and reporting"/><div className="sourceflow"><div className="sourcebox"><b>Internal Portfolio Data</b><span>• Trades</span><span>• Holdings</span><span>• Client details</span><span>• Cash ledger</span></div><div className="plus">+</div><div className="sourcebox external"><b>External Market Data Feed</b><span>• Security prices</span><span>• FX rates</span><span>• Market indices</span><small>Prototype: fixed historical dataset</small></div><div className="merge">↓</div><div className="node wide"><b>1</b><span>Portfolio Valuation &amp; MTM Engine</span></div><div className="arrow">↓</div><div className="node wide"><b>2</b><span>Benchmark &amp; Risk Engine</span></div><div className="arrow">↓</div><div className="node wide"><b>3</b><span>Client Dashboard &amp; Statement Reporting</span></div></div><div className="explain"><b>How to explain it:</b> Internal portfolio data and the external market-data feed come together in the valuation engine. The system calculates current value and MTM, then benchmark and risk metrics, and finally produces the dashboard and client statement. For this prototype, the external feed is simulated with fixed historical data; production can connect this layer to an approved provider such as Bloomberg.</div></div>
}
createRoot(document.getElementById("root")).render(<App/>);
